config/routes.rb
Rails.application.routes.draw do
 
  resources :records
  get 'search/index'

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get '/reactJS',     to: 'static_pages#reactJS'
  get '/signup',   to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'  
  delete '/logout',to: 'sessions#destroy'
  get 'results', to: 'users#index', as: 'results'
  get '/auth/vkontakte/callback', to: 'omniauth#create'
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :microposts do
    member do
      get :like, :unlike
    end
  end
  
 
  #,          only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
     <div class="alert alert-danger">
      Форма содержит <%= pluralize(object.errors.count, "ошибки") %>.
    </div> 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ol class="microposts">
  <%= render @feed_items %>
</ol>
<%= will_paginate @feed_items %>
<% end %> 

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
  <%= f.text_area :content, placeholder: "Напишите здесь что нибудь..." %>
</div>
<%= f.submit "Опубликовать", class: "btn btn-primary" %>
<span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_shared.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    читаемые
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    читатели
  </a>
  
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    читаемые
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    читатели
  </a>
  
</div>

app/views/shared/_user_info.html.haml
= link_to image_tag(gravatar_for(@user, size: 100), alt: @user.name, class: "gravatar"), @user
%h1= link_to "#{@user.name}", @user
%span
  - pluralize(@user.microposts.count, "новост")