config/routes.rb
Rails.application.routes.draw do
 
  resources :records
  get 'search/index'

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get '/reactJS',     to: 'static_pages#reactJS'
  get '/signup',   to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'  
  delete '/logout',to: 'sessions#destroy'
  get 'results', to: 'users#index', as: 'results'
  get '/auth/vkontakte/callback', to: 'omniauth#create'
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :microposts do
    member do
      get :like, :unlike
    end
  end
  
 
  #,          only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  acts_as_votable cacheable_strategy: :update_columns
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate  :picture_size
  

  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end  

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :like, :unlike]
  before_action :correct_user, only: :destroy
  
  
  
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Новость добавлена"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end
  
  def destroy
    @micropost.destroy
    flash[:success] = "Новость удалена"
    redirect_to request.referrer || root_url
  end
  
  def like
    @micropost = Micropost.find(params[:id])
    @micropost.like_by current_user
    respond_to do |format|
      format.html {redirect_to :back }
      format.js
    end
  end
  
  def unlike
    @micropost = Micropost.find(params[:id])
    @micropost.unliked_by current_user
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end
  
  private
 
  def micropost_params
    params.require(:micropost).permit(:content, :picture)
  end
  
  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
  
  def display_likes(micropost)
    votes = micropost.votes_for.up.by_type(User)
    return list_likers(votes) if votes.size <= 8
  end
  
  private
  
  def list_likers(votes)
    usernames = []
    unless votes.blank?
      votes.voters.each do |voter|
        usernames.push(link_to voter.name,
        user_path(voter.id),
        class: 'username')
      end
      usernames.to_sentence.html_safe + like_plural(votes)
    end
  end
  
  def count_likers(votes)
    vote_count = votes.size
    vote_count.to_s + ' likes'
  end
  
  def like_plural(votes)
    return ' like this' if votes.count > 1
    ' понравилось'
  end
  
end

app/views/microposts/_likes.html.erb
<% if !logged_in?  %>
<%=  display_likes micropost %>
<% elsif current_user.liked? micropost %>
  <%= link_to '', unlike_micropost_path(micropost.id), remote: true,
                        id: "unlike_#{micropost.id}",
                        class: "glyphicon glyphicon-heart" %>
    <%=  display_likes micropost %>
<% else %>
  <%= link_to '', like_micropost_path(micropost.id), remote: true,
                        id: "like_#{micropost.id}",
                        class: "glyphicon glyphicon-heart-empty" %>

    <%=  display_likes micropost %>
  <% end %>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to image_tag(gravatar_for(micropost.user, size: 50), alt: micropost.user.name, class: "gravatar"), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
    <div class="likes" id="likes_<%= micropost.id %>">
    <%=  render "microposts/likes", micropost: micropost %>
    </div>
    </span>
    
  <span class="timestamp">
    Опубликовано <%= time_ago_in_words(micropost.created_at) %> назад.
    <% if current_user?(micropost.user) %>
      <%= link_to "удалить", micropost, method: :delete,
                                        data: { confirm: "Уверены?"} %>
      <% end %>
  </span>
  
</li>

app/views/microposts/like.js.erb
$("#like_<%= @micropost.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#like_<%= @micropost.id %>").attr("href", '/events/<%= @micropost.id %>/unlike');
$("#likes_<%= @micropost.id %>").html("<%= j (render partial: 'microposts/likes', locals: { micropost: @micropost } ) %>");

app/views/microposts/unlike.js.erb
$("#unlike_<%= @micropost.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#unlike_<%= @micropost.id %>").attr("href", '/events/<%= @micropost.id %>/like');
$("#likes_<%= @micropost.id %>").html("<%= j (render partial: 'microposts/likes', locals: { micropost: @micropost } ) %>");