config/routes.rb
Rails.application.routes.draw do
 
  resources :records
  get 'search/index'

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get '/reactJS',     to: 'static_pages#reactJS'
  get '/signup',   to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'  
  delete '/logout',to: 'sessions#destroy'
  get 'results', to: 'users#index', as: 'results'
  get '/auth/vkontakte/callback', to: 'omniauth#create'
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :microposts do
    member do
      get :like, :unlike
    end
  end
  
 
  #,          only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
      <div class="container">
        <%= link_to "sample app", root_path, id: "logo" %>
        <nav >
          <ul class="collapse navbar-collapse nav navbar-nav navbar-right">
            <li><%= link_to "Главная", root_path %></li>
            <li><%= link_to "ReactJS",   reactJS_path %></li>
            <% if logged_in? %>
            <li><%= link_to "Поиск", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Аккаунт <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Профиль", current_user %></li>
                <li><%= link_to "Настройки", edit_user_path(current_user) %></li>
                <li>
                  <%= link_to "Выйти", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
            <% else %>
              <li><%= link_to "Войти", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %> 
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>